### ISSUE TITLE
just how

### ISSUE THREAD

**Issue by lesha-co** [DieKatzchen/GuideButtonPoller#1]
How did you do that? 
I mean, here:  
`FARPROC lpfnGetProcessID = GetProcAddress(HMODULE(hGetProcIDDLL), (LPCSTR)100);`
What have you done? You accessed function (other than [XInputGetState](http://msdn.microsoft.com/en-us/library/windows/desktop/microsoft.directx_sdk.reference.xinputgetstate%28v=vs.85%29.aspx)), which Microsoft hasn't exported in XInput library? Kind of private API?

Anyway, thank you for this line of code, because XInputGetState doesn't provide support for guide button.

**Comment by DasKatzchen** [comment]
It's an unnamed function, so I'm actually accessing it by ordinal.  It's ordinal 100.  Ordinal 103 lets you turn a wireless controller off.  I've never figured out what 101 and 102 do.
